### ISSUE TITLE
Failed to handle method call

### ISSUE THREAD

**Issue by Wahid11041** [TrangLeQuynh/flutter-upgrade-version#37]
gradle-7.4
tools.build:gradle:7.3.0
kotlin_version = '1.9.0'

Flutter 3.19.3
Dart 3.3.1

**Comment by Wahid11041** [comment]
E/MethodChannel#com.tranglequynh.flutter-upgrade-version/in-app-update(15425): Failed to handle method call
E/MethodChannel#com.tranglequynh.flutter-upgrade-version/in-app-update(15425): java.lang.IllegalArgumentException: kotlin.Unit
E/MethodChannel#com.tranglequynh.flutter-upgrade-version/in-app-update(15425): 	at com.tranglequynh.flutter_upgrade_version.InAppUpdateHandler.startAnUpdate(InAppUpdateHandler.kt:106)
E/MethodChannel#com.tranglequynh.flutter-upgrade-version/in-app-update(15425): 	at com.tranglequynh.flutter_upgrade_version.InAppUpdateHandler.onMethodCall(InAppUpdateHandler.kt:61)
E/MethodChannel#com.tranglequynh.flutter-upgrade-version/in-app-update(15425): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#com.tranglequynh.flutter-upgrade-version/in-app-update(15425): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#com.tranglequynh.flutter-upgrade-version/in-app-update(15425): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#com.tranglequynh.flutter-upgrade-version/in-app-update(15425): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#com.tranglequynh.flutter-upgrade-version/in-app-update(15425): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#com.tranglequynh.flutter-upgrade-version/in-app-update(15425): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#com.tranglequynh.flutter-upgrade-version/in-app-update(15425): 	at android.os.Looper.loopOnce(Looper.java:210)
E/MethodChannel#com.tranglequynh.flutter-upgrade-version/in-app-update(15425): 	at android.os.Looper.loop(Looper.java:299)
E/MethodChannel#com.tranglequynh.flutter-upgrade-version/in-app-update(15425): 	at android.app.ActivityThread.main(ActivityThread.java:8261)
E/MethodChannel#com.tranglequynh.flutter-upgrade-version/in-app-update(15425): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.tranglequynh.flutter-upgrade-version/in-app-update(15425): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
E/MethodChannel#com.tranglequynh.flutter-upgrade-version/in-app-update(15425): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
E/DartMessenger(15425): Uncaught exception in binary message listener
E/DartMessenger(15425): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(15425): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:431)
E/DartMessenger(15425): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:287)
E/DartMessenger(15425): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/DartMessenger(15425): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/DartMessenger(15425): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DartMessenger(15425): 	at android.os.Handler.handleCallback(Handler.java:942)
E/DartMessenger(15425): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/DartMessenger(15425): 	at android.os.Looper.loopOnce(Looper.java:210)
E/DartMessenger(15425): 	at android.os.Looper.loop(Looper.java:299)
E/DartMessenger(15425): 	at android.app.ActivityThread.main(ActivityThread.java:8261)
E/DartMessenger(15425): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(15425): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
E/DartMessenger(15425): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
D/DecorView[](15425): getWindowModeFromSystem  windowmode is 1
D/DecorView[](15425): updateDecorCaptionStatus windowMode is 1
D/FRCPlugin(15425): Sending fetchTimeout: 60

**Comment by TrangLeQuynh** [comment]
Have you called `checkForUpdate` before starting the update?

**Comment by TrangLeQuynh** [comment]
Please share your code implementation.

**Comment by TrangLeQuynh** [comment]
- You need ensure that has the same application ID and signing key.
- Have you called the check Update Status before starting an update?
